import {TenantClient} from '../../models/tenant-client';

export const MOCK_CLIENTS: Array<TenantClient> = [
  {
    clientId: '1',
    surename: 'Mustermann',
    firstname: 'Max',
    phone: '0123-456 789',
    zipCode: '12345',
    infected: true,
    healthDepartmentId: '1',
    comments: [],
    state: 'ok',
  },
  {
    clientId: '2',
    surename: 'Musterfrau',
    firstname: 'Erika',
    phone: '0171-47538521',
    zipCode: '12345',
    infected: true,
    healthDepartmentId: '1',
    comments: [],
    state: 'bodyTemperatureRaised'
  },
  {
    clientId: '1',
    surename: 'Irgendwas',
    firstname: 'Alfred',
    phone: '0123-547821',
    zipCode: '12345',
    infected: false,
    healthDepartmentId: '1',
    comments: [],
    state: 'missingComment',
  },
  {
    clientId: '2',
    surename: 'Musterfrau',
    firstname: 'Erika',
    phone: '0171-47538521',
    zipCode: '12345',
    infected: true,
    healthDepartmentId: '1',
    comments: [],
    state: 'bodyTemperatureRaised'
  },
  {
    clientId: '1',
    surename: 'Irgendwas',
    firstname: 'Alfred',
    phone: '0123-547821',
    zipCode: '12345',
    infected: false,
    healthDepartmentId: '1',
    comments: [],
    state: 'missingComment',
  },
  {
    clientId: '2',
    surename: 'Musterfrau',
    firstname: 'Erika',
    phone: '0171-47538521',
    zipCode: '12345',
    infected: true,
    healthDepartmentId: '1',
    comments: [],
    state: 'bodyTemperatureRaised'
  },
  {
    clientId: '1',
    surename: 'Irgendwas',
    firstname: 'Alfred',
    phone: '0123-547821',
    zipCode: '12345',
    infected: false,
    healthDepartmentId: '1',
    comments: [],
    state: 'missingComment',
  },
  {
    clientId: '2',
    surename: 'Musterfrau',
    firstname: 'Erika',
    phone: '0171-47538521',
    zipCode: '12345',
    infected: true,
    healthDepartmentId: '1',
    comments: [],
    state: 'bodyTemperatureRaised'
  },
  {
    clientId: '1',
    surename: 'Irgendwas',
    firstname: 'Alfred',
    phone: '0123-547821',
    zipCode: '12345',
    infected: false,
    healthDepartmentId: '1',
    comments: [],
    state: 'missingComment',
  },
  {
    clientId: '2',
    surename: 'Musterfrau',
    firstname: 'Erika',
    phone: '0171-47538521',
    zipCode: '12345',
    infected: true,
    healthDepartmentId: '1',
    comments: [],
    state: 'bodyTemperatureRaised'
  },
  {
    clientId: '1',
    surename: 'Irgendwas',
    firstname: 'Alfred',
    phone: '0123-547821',
    zipCode: '12345',
    infected: false,
    healthDepartmentId: '1',
    comments: [],
    state: 'missingComment',
  },
  {
    clientId: '2',
    surename: 'Musterfrau',
    firstname: 'Erika',
    phone: '0171-47538521',
    zipCode: '12345',
    infected: true,
    healthDepartmentId: '1',
    comments: [],
    state: 'bodyTemperatureRaised'
  },
  {
    clientId: '1',
    surename: 'Irgendwas',
    firstname: 'Alfred',
    phone: '0123-547821',
    zipCode: '12345',
    infected: false,
    healthDepartmentId: '1',
    comments: [],
    state: 'missingComment',
  },
  {
    clientId: '2',
    surename: 'Musterfrau',
    firstname: 'Erika',
    phone: '0171-47538521',
    zipCode: '12345',
    infected: true,
    healthDepartmentId: '1',
    comments: [],
    state: 'bodyTemperatureRaised'
  },
  {
    clientId: '1',
    surename: 'Irgendwas',
    firstname: 'Alfred',
    phone: '0123-547821',
    zipCode: '12345',
    infected: false,
    healthDepartmentId: '1',
    comments: [],
    state: 'missingComment',
  }
];
